### PR TITLE
Updated index page and styling, fixed All-Ears banner for mobile screens

### PR DESCRIPTION
**Pull request by lochem2-718**

### CODE REVIEW

**Comment by lochem2-718** [comment]
I got the new elephant image from wikimedia commons, which has no copyright

**Review by slf279 — CHANGES_REQUESTED** [review]
Can you change the All Ears logo to be centered in its container in index.html? Can you also alter the logo caption so that it is centered on the image? It would also be a good idea to make the descriptive text fill in more of the box it resides in; there's too much white space there. It might also be a good idea to change the smaller text under the white 'All Ears' to have every word capitalized for consistency and aesthetics, but I'll leave that up to you. 

Also! We want the 'mission statement' to be one of the things that catches our audiences' eye! Having to scroll down to see it on a browser feels counter-intuitive. I would suggest moving it up so that scrolling isn't at all necessary on this page, reducing the size of the logo so that the container can shrink and the background photo isn't eclipsed by the content. Any other information we add to the page will be secondary to the mission and can stand to be scrolled down to (such as direct links to general donation websites and/or other organizations' information pages about poaching if we want to go that far.

The descriptive text could also be improved for readability and directness. I suggest "Through this project, we intend to educate the public about the threat of forest elephant poaching and its devastating effects on the the rainforest environments of the Congo Basin and on global warming. Our project will also provide ways for the public to help fight back against forest elephant poaching by offering donation opportunities to accredited elephant-centric anti-poaching organizations." It is less vague about how the public can get involved through our product.

**Comment by lochem2-718** [comment]
I implemented your changes except for putting the logo in the center.

**Comment by lochem2-718** [comment]
I think this iteration looks a lot better. Tell me what you think!

**Pull request merged**
